export const privacyDefault = `<h2>Copyright</h2>
<p>Tutte le immagini ed i dati contenuti in questo www.associazionesanabel.org sono di titolarità esclusiva di Sanabel APS, ne è pertanto vietata la riproduzione, permanente o temporanea, l'adattamento, la diffusione, la distribuzione al pubblico senza il preventivo ed espresso consenso del titolare dei diritti d'autore.</p>
<h2>Norme sulla Privacy</h2>
<p>Proteggere la sicurezza e la privacy dei vostri dati personali è importante per Sanabel APS, che agisce in conformità con le leggi attualmente sulla protezione e sulla Sicurezza dei dati personali in vigore. Confidiamo che le norme sotto riportate vi aiutino a capire quale genere di dati Sanabel APS è solita raccogliere, come li utilizzi e li salvaguardi e con chi li condivida.</p>
<h2>Dati personali </h2>
<p>Tramite il proprio sito web, Sanabel APS non raccoglie alcun Vostro dato personale (es. nome, indirizzo, telefono, indirizzo e-mail), a meno che Voi non acconsentiate a fornirlo volontariamente (per es. mediante una registrazione al sito od un sondaggio). Ogni consenso può essere revocato in qualsiasi momento. Avrete la facoltà di esercitare i diritti previsti dall'art. 7 del Lgs 196/03 e s.m.i., in particolare modo avrete diritto di recedere dalla registrazione in qualsiasi momento e senza alcuna penale.</p>
<h2>Scopo del trattamento </h2>
<p>A seguito di quanto prescritto dalla legge 30 giugno 2003 n. 196 e s.m.i.  " Codice in materia di protezione dei dati personali", Vi segnaliamo le finalità e modalità di trattamento cui sono destinati i dati personali da Voi eventualmente forniti.<br />
Ai sensi dell'art. 13 della legge citata, tali dati saranno oggetto da parte nostra di trattamenti informatici o manuali come definito dall'art. 4, comma 1, lettera <br />
a) della legge, per finalità di: a) adempimenti di legge connessi a norme civilistiche, fiscali, contabili, ecc., gestione amministrativa del rapporto, adempimento di eventuali obblighi contrattuali, supporto ed informazione tecnica in merito ai prodotti ed ai servizi oggetto del rapporto;<br />
 b) assistenza post-vendita, verifica soddisfazione degli utenti, analisi di mercato e statistiche;<br />
 c) informazione su future attività commerciali ed annunci di nuovi prodotti, servizi ed offerte, sia da parte nostra che da parte di società nostre consociate; <br />
d) iniziative promozionali e pubblicitarie destinate al mercato;<br />
 e) eventuali analisi e valutazioni economico-finanziarie.<br />
Sanabel APS non raccoglierà in alcun caso i dati "sensibili" di cui all'art. 26 della Legge 196/03 e s.m.i. Il titolare del trattamento dei dati è: Sanabel APS.  Via Santa Cesarea 59 Matera. Partita Iva/C.F.: 93070890772.</p>
<h2>Dati relativi all’Utilizzo o alla Comunicazione</h2>
<p>Nell'utilizzare i servizi di telecomunicazione che consentono di accedere al nostro sito Web, i dati relativi al tipo di comunicazione (es., indirizzi IP) o all’utilizzo (es., le informazioni sull’inizio, il termine e la durata di ogni accesso, e quelle relative ai servizi di telecomunicazione ai quali ci si è collegati) generati tecnicamente potrebbero essere ragionevolmente correlati a dati personali. La raccolta e l’elaborazione di tali dati avverrà solo in caso di necessità e sarà comunque eseguita in ottemperanza ai disposti della Legge 196/03 e s.m.i.</p>
<h2>Raccolta Automatica dei Dati Non Personali </h2>
<p>Quando accedete al sito web di www.associazionesanabel.org, in modo automatico (anche senza registrazione) vengono raccolti dal nostro sistema alcune informazioni che, peraltro, non portano ad un’identificazione personale (es. tipo di browser internet e di sistema operativo usato; dominio del sito web dal quale siete arrivati al sito www.associazionesanabel.org, numero di visite al sito, media di tempo trascorsa, pagine visitate). Sanabel APS potrebbe utilizzare queste informazioni e condividerle a livello mondiale con le società del Gruppo, al fine di verificare l’utilizzo del sito web e migliorarne le performances ed i contenuti.</p>
<h2>"Cookie": informazioni memorizzate automaticamente sul Vostro PC </h2>
<p>Quando visitate uno dei nostri siti Web, potremmo immagazzinare alcuni dati sul vostro computer sotto forma di “cookie” per riconoscere automaticamente il vostro PC alla prossima visita. I cookie possono esserci di aiuto in diversi modi, per esempio consentendoci di modificare un sito Web affinché risponda ai vostri interessi o di salvare la vostra password per risparmiarvi di dovere ripetere la procedura ad ogni accesso. Se non desiderate ricevere cookie, non dovete fare altro che configurare il vostro browser Internet affinché cancelli tutte i cookie dall’hard disk del computer, li blocchi o generi un avviso tutte le volte che ne viene salvato uno.</p>
<h2>Minori </h2>
<p>Nessun dato personale dovrebbe essere inserito sul sito della Sanabel APS da minori senza il preventivo consenso dei genitori o dei tutori. Sanabel APS incoraggia tutti i genitori e i tutori ad istruire i minori sull’uso in Internet dei propri dati personali in modalità sicura e responsabile. Sanabel APS, comunque si impegna a non conservare od usare consapevolmente nessun dato personale raccolto da minori per nessun fine, inclusa la divulgazione a terze parti.</p>
<h2>Sicurezza </h2>
<p>Per proteggere i vostri dati personali contro la distruzione, la perdita o l’alterazione accidentale o impropria, e contro l’accesso o la divulgazione non autorizzati, Sanabel APS ha previsto misure di sicurezza di natura tecnica e organizzativa.</p>
<h2>Link ad altri Siti Web </h2>
<p>Sulle pagine web di <a href="http://www.associazionesanabel.org" target="_blank" rel="noopener noreferrer">www.associazionesanabel.org</a> si possono trovare collegamenti ipertestuali (Hyperlink) con altri siti web, proposti per fornire un migliore servizio ai propri utenti.<br />
Sanabel APS non è in alcun modo responsabile del contenuto dei siti web ai quali gli utenti dovessero eventualmente accedere tramite il proprio sito. L’esistenza di un Hyperlink verso un altro sito non sottintende quindi approvazione od accettazione di responsabilità da parte di Sanabel APS circa il contenuto del nuovo sito cui si accede, anche in relazione alla politica adottata per il trattamento dei dati personali, nonché alla sua utilizzazione.</p>
<h2>Domande e Commenti </h2>
<p>Sanabel APS si impegna a rispondere a qualunque ragionevole richiesta relativa alla revisione dei dati personali e a correggere, emendare o cancellare eventuali inesattezze. Qualora abbiate delle domande o dei commenti da sottoporre in merito alla Sanabel APS Data Privacy Protection Policy – Norme di Protezione dei Dati Personali di Sanabel APS (es. per rivedere e aggiornare i vostri dati personali), cliccate su “Contacts” nell’angolo in alto a destra di questa schermata e compilate il form allegato. Sanabel APS si impegna a inserire in questa pagina, nel minor tempo possibile, ogni cambiamento alla Sanabel APS Data Privacy Protection Policy – Norme di Protezione dei Dati Personali di Associazione Sanabel APS, qualora essa venisse modificata.</p>
<h2>Informativa Cookies</h2>
<p>Informativa ai sensi del Provvedimento “Individuazione delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie” dell’ 08 maggio 2014.1.</p>
<h3>1) Perché questo avviso?</h3>
<p>In questa pagina si descrivono le modalità di gestione del sito web di Sanabel APS (di seguito per brevità Sanabel APS in riferimento ai cookie che vengono installati sui terminali degli utenti stessi. Si tratta di un'informativa estesa, ai sensi del combinato disposto degli artt. 13, comma 3, 122, comma 1 e 154, comma 1, lett. c), del Codice, al fine di fornire, volta ad informare l’utente in merito all'archiviazione dei c.d. cookie sul suo terminale da parte del presente sito internet visitato e ciò in conformità del Provvedimento dell’08 maggio 2014 in merito “Individuazione delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie”. Il presente documento riprende volutamente i contenuti della Privacy Policy applicata dall’Autorità Garante per la protezione dei dati personali con riferimento al trattamento di dati personali degli utenti che si collegano al sito web ufficiale www.garanteprivacy.it. È difatti intenzione del titolare conformare le proprie politiche di tutela della privacy a quanto previsto dal “Codice”, anche alle cautele ed alle procedure che il Garante ha specificato proprio nel documento sulla Privacy Policy pubblicato sul sito web ufficiale dell’Autorità, in merito al alla Privacy ti invitiamo a leggere la Privacy Policy del nostro sito, nonché al Provvedimento “Individuazione delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie” dell’08 maggio 2014</p>
<h3>2) Utilizzo di tecnologie per acquisire informazioni archiviate negli apparecchi terminali degli Utenti (“Informativa Cookies”)</h3>
<p>Abbiamo predisposto la seguente Policy sui Cookies per descrivere i tipi di cookies e altre tecnologie usate sul nostro Sito e sulla nostra piattaforma e per descrivere i motivi e le condizioni di utilizzo dei cookies. Ti preghiamo di notare che non possiamo offrire il nostro Sito o i nostri Servizi senza inviare sul tuo dispositivo alcuni dei nostri cookies e/o simili tecnologie. Pertanto tu ci autorizzi a usare i cookies di Sanabel APS quando utilizzi il nostro Sito e i nostri Servizi. Tuttavia, puoi evitare alcuni cookies configurando le impostazioni del tuo browser oppure rifiutando direttamente rispetto a terzi, come specificato nel dettaglio di seguito.</p>
<h3>A. Che cosa sono i Cookies?</h3>
<p>I cookies sono piccoli file di testo che si trovano sulla directory del tuo browser. Quando si accede a un sito web, un cookie che viene inviato sul dispositivo tramite cui si accede al sito web invia informazioni al browser. I cookies sono molto comuni e sono utilizzati su numerosi siti web. Questo accade poiché i cookies permettono a chi gestisce il sito web di fare cose utili; per esempio, un cookie consente al gestore di un sito web di sapere se un computer (e probabilmente il relativo utente) ha visitato il sito web in precedenza. In genere, la finalità dei cookies è migliorare il funzionamento del sito web e l'esperienza dell'utente nell'utilizzo dello stesso, anche se i cookies possono anche inviare messaggi pubblicitari (come di seguito specificato). Il presente documento riprende volutamente i contenuti della Privacy Policy applicata dall'Autorità Garante per la protezione dei dati personali con riferimento al trattamento di dati personali degli Utenti, pubblicata sul Sito web ufficiale <a href="http://www.garanteprivacy.it/" target="_blank" rel="noopener noreferrer">www.garanteprivacy.it</a></p>
<h3>B. Cookies Tecnici e Cookies di Terzi</h3>
<p>Possiamo inviare cookies di Sanabel APS sul tuo dispositivo tramite il nostro Sito. I Cookies che inviamo sono definiti cookies Tecnici. I cookies Tecnici sono cookies che appartengono al Sito che li ha creati. L'utilizzo di tali cookies ci permette di far funzionare il Sito in modo efficiente. Consentiamo anche a terzi di inviare cookies sul tuo dispositivo. La differenza tra un cookie Tecnico del sito e un cookie di terzi riguarda il controllo da parte del soggetto che invia il cookie. Anche se consentiamo a terzi di accedere al Sito per inviare i cookies sul dispositivo dell'utente, non abbiamo il controllo sulle informazioni fornite dai cookies e non abbiamo accesso a tali dati. Queste informazioni sono controllate totalmente da terzi secondo quanto descritto nella sopra estesa privacy policy.</p>
<h3>C. Cookies di Sessione e Cookies Persistenti</h3>
<p>Il nostro Sito può inviare cookies di sessione e persistenti sul tuo dispositivo. Mentre la differenza tra un cookie Tecnico e un cookie di terzi riguarda il soggetto che controlla l'invio iniziale del cookie sul tuo dispositivo, la differenza tra un cookie di sessione e un cookie persistente riguarda il diverso lasso di tempo per cui un cookie opera. I cookies di sessione sono cookies che tipicamente durano finché chiudi il tuo internet browser. Quando finisci la tua sessione browser, il cookie scade. I cookies persistenti, come lo stesso nome indica, sono cookies costanti e continuano ad operare dopo che hai chiuso il tuo browser. Questo consente un accesso più rapido e più agevole al nostro Sito. Per esempio, un cookie persistente che il nostro Sito legge dal tuo dispositivo è la lingua prescelta per la navigazione. Dopo l'invio del cookie, questo consente che in occasione di tuoi futuri accessi al Sito tu venga automaticamente indirizzato al sito con la lingua prescelta.</p>
<h3>D. Cookies e Altre Tecnologie sul Sito di Sanabel APS</h3>
<p>Il nostro Sito può inviarti cookies e simili tecnologie in diversi modi e per diverse finalità. In genere, queste comprendono:</p>
<p>• Per semplificare il tuo utilizzo del nostro Sito e dei nostri Servizi;</p>
<p>• Per monitorare, analizzare e migliorare il funzionamento e l'efficienza del nostro Sito e dei nostri Servizi;</p>
<p>E' nostra intenzione essere trasparenti e chiari su condizioni e finalità del nostro utilizzo di cookies e altre tecnologie. Pertanto, in questa sezione abbiamo specificato i cookies che rilevano per il tuo utilizzo del nostro Sito e dei nostri Servizi.</p>
<h3>D.1. Cookies di Sito</h3>
<p>I cookies di sito sono cookies inviati dai server di Sanabel APS per consentire l'utilizzo del Sito. Questi cookies sono generalmente conservati sul tuo browser e non scadono alla fine della tua sessione. I cookies di tracciamento dell'utente sono cookies Tecnici che tracciano ID e impostazioni dell'utente in occasione della visita e dell'utilizzo del Sito. Consideriamo questi cookies utili al funzionamento del nostro Sito e possiamo inviarli sul tuo dispositivo per migliorare il tuo utilizzo del nostro Sito e dei nostri Servizi.</p>
<h3>D.2. Google Analytics</h3>
<p>Utilizziamo Google Analytics, un servizio di web analytics fornito da Google che invia cookies sul tuo dispositivo. Le informazioni generate dal cookie sul tuo utilizzo del Sito<strong> (tranne il tuo indirizzoIP in quanto questo sito è dotato di sistemi che lo rendono anonimo) </strong>sono trasmesse a Google e conservate da Google su server negli Stati Uniti. Google utilizza queste informazioni per valutare il tuo utilizzo del Sito, predisporre resoconti sull'attività del sito web per operatori di siti web e per fornire altri servizi relativi all'attività del sito web e all'utilizzo di internet. Google può anche trasferire queste informazioni a terzi se richiesto dalla legge oppure in caso di terzi che elaborano queste informazioni per conto di Google. Google non associa il tuo indirizzo IP con nessun altro dato che Google possiede. Google è il relativo Titolare del trattamento. Per ulteriori informazioni su Google Analytics, puoi consultare <a href="https://developers.google.com/analytics/resources/concepts/gaConceptsCookies" target="_blank" rel="noopener noreferrer">Cookies and Analytics</a> e la relativa privacy policy per <a href="http://www.google.com/analytics/learn/privacy.html" target="_blank" rel="noopener noreferrer">Google Analytics</a>.</p>
<p>- _utma – Cookie di terze parti – Google inc. – Durata: 2 Anni/Aggiornato - Utilizzato per distinguere gli utenti e sessioni. Il cookie viene creato all'esecuzione della libreria javascript. Questo cookie tiene traccia del numero di volte che un visitatore ha visitato il sito web, quando ha effettuato la prima visita e quando si è verificata l’ultima. Il cookie viene aggiornato ogni volta che i dati vengono inviati a Google Analytics.</p>
<p>- _utmb – Cookie di terze parti – Google inc. – Durata: 30 minuti/Aggiornato – Utilizzato per determinare nuove sessioni / visite. Recupera il timestamp nel momento esatto in cui un visitatore entra nel sito. Il cookie viene aggiornato ogni volta che i dati vengono inviati a Google Analytics.</p>
<p>- _utmc – Cookie di terze parti – Google inc. – Durata: fine della sessione – Questo cookie opera in collaborazione con il cookie _utmb per determinare se l'utente ha creato una nuova sessione oppure se sta visitando nuovamente il sito.</p>
<p>- _utmz – Cookie di terze parti – Google inc. – Durata: 6 mesi/Aggiornato – Memorizza la fonte di traffico o campagna dalla quale l'utente ha raggiunto il sito. Il cookie viene creato quando all'esecuzione della libreria javascript e viene aggiornato ogni volta che i dati vengono inviati a Google Analytics.</p>
<p>- _utmv – Cookie di terze parti – Google inc. – Durata: 2 anni/Aggiornato – Utilizzato per memorizzare a livello di visitatore dati variabili personalizzati. Viene aggiornato ogni volta che i dati vengono inviati a Google Analytics.</p>
<p>- _ga – Cookie di terze parti – Google inc. – Durata: 2 anni – Utilizzato per distinguere gli utenti.</p>
<h3>E. Trasparenza nell'uso di cookie</h3>
<p>Vogliamo rendere l'uso di cookie e delle altre tecnologie simili il più trasparente possibile. Come specificato sopra, non siamo in grado di offrirti il Sito ed i nostri Servizi senza i cookie Sanabel APS. Se non desideri ricevere cookie di terzi sul tuo dispositivo molti di questi offrono possibilità per escluderne il ricevimento. Ti preghiamo di notare, tuttavia, che tale esclusione per mezzo di terzi non è soggetta al nostro controllo.</p>
<h3>E.1 Come disabilitare i cookies di terze parti?</h3>
<p>Ai sensi dell’art. 154 comma 1 lett. C) del Codice della privacy si riportano di seguito i link alle pagine web contenenti le informative adottate dalle terze parti:</p>
<p>Google: <a href="https://www.google.it/intl/it/policies/privacy/?fg=1" target="_blank" rel="noopener noreferrer">Norme sulla privacy di Google</a></p>
<h3>E.2 Come disabilitare i cookies dai principali browser?</h3>
<p>La maggior parte dei browser (Internet Explorer, Firefox, Chrome, ecc.) sono configurati per accettare i cookies. I cookies memorizzati sul disco fisso del tuo dispositivo possono comunque essere cancellati ed è inoltre possibile disabilitare i cookies seguendo le indicazioni fornite dai principali browser, ai link seguenti:</p>
<p>Chrome: <a href="https://support.google.com/chrome/answer/95647?hl=it" target="_blank" rel="noopener noreferrer">https://support.google.com/chrome/answer/95647?hl=it</a></p>
<p>Firefox: <a href="http://support.mozilla.org/it/kb/Eliminare%20i%20cookie" target="_blank" rel="noopener noreferrer">http://support.mozilla.org/it/kb/Eliminare%20i%20cookie</a></p>
<p>Internet Explorer: <a href="http://windows.microsoft.com/it-it/internet-explorer/delete-manage-cookies#ie=ie-10" target="_blank" rel="noopener noreferrer">http://windows.microsoft.com/it-it/internet-explorer/delete-manage-cookies#ie=ie-10</a></p>
<p>Opera: <a href="http://www.opera.com/help/tutorials/security/privacy/" target="_blank" rel="noopener noreferrer">http://www.opera.com/help/tutorials/security/privacy/</a></p>
<p>Safari: <a href="http://support.apple.com/kb/ph11920" target="_blank" rel="noopener noreferrer">http://support.apple.com/kb/ph11920</a></p>
<p>Ai sensi dell’articolo 122, comma 1, del Codice della Privacy (nella formulazione vigente a seguito della entrata in vigore del d.lgs. 69/2012) e del Provvedimento del Garante Privacy “Individuazione delle modalità semplificate per l’informativa e l’acquisizione del consenso per l’uso dei cookie” dell’08 maggio 2014, i cookies "tecnici" possono essere utilizzati anche in assenza del consenso dell’interessato. Tra l’altro, lo stesso organismo europeo che riunisce tutte le Autorità Garanti per la privacy dei vari Stati Membri (il c.d. Gruppo "Articolo 29") ha chiarito nel Parere 4/2012 (WP194) intitolato “Esenzione dal consenso per l’uso dei cookies” che sono cookies per i quali non è necessario acquisire il consenso preventivo e informato dell'utente:</p>
<p>- cookies con dati compilati dall'utente (identificativo di sessione), della durata di una sessione o cookies persistenti limitatamente ad alcune ore in taluni casi;</p>
<p>- cookies per l'autenticazione, utilizzati ai fini dei servizi autenticati, della durata di una sessione;</p>
<p>- cookies di sicurezza incentrati sugli utenti, utilizzati per individuare abusi di autenticazione, per una durata persistente limitata;</p>
<p>- cookies di sessione per lettori multimediali, come i cookies per lettori "flash", della durata di una sessione;</p>
<p>- cookies di sessione per il bilanciamento del carico, della durata di una sessione;</p>
<p>- cookies persistenti per la personalizzazione dell'interfaccia utente, della durata di una sessione (o poco più);</p>
<p>- cookies per la condivisione dei contenuti mediante plug-in sociali di terzi, per membri di una rete sociale che hanno effettuato il login.</p>
<h3>3. Modifiche a questa Informativa Cookies</h3>
<p>Sanabel APS si riserva il diritto di apportare cambiamenti al Sito, alla presente Informativa Cookies ovunque pubblicata nel Sito, in qualsiasi momento. All’atto della consultazione, l’utente dovrà sempre fare riferimento, come vigente versione, al testo pubblicato.</p>
<p>Le modifiche diventeranno operative nel momento in cui verranno pubblicate sul Sito. Il proseguimento dell’uso del Sito da parte dell’utente, a seguito di una modifica, verrà considerato come un’accettazione di tali modifiche.</p>
<p>Tutti gli utenti potranno verificare in qualsiasi momento, collegandosi al Sito, l'ultima versione della Informativa Cookies come di volta in volta aggiornata da Sanabel APS.</p>
`;
